# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
     Greeting: Hello
     DAY_OF_WEEK: monday
     First_Name: niraj

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: | 
           echo Hello, world!
           echo hi 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $Greeting $First_Name. Today is $DAY_OF_WEEK!
          echo ${{ github.run_id }}
          echo ${{ github.event.repository.name }}

          
      - name: create dir
        run: mkdir /tmp/artifacts
        
      - name: "List file"
        shell: bash
        run: |
          ls -R
        
      - name: Copy file
        # You may pin to the exact commit or the version.
        # uses: canastro/copy-action@7ddff6fc153a2ea2cd0fb88ed9750544c051e399
        uses: canastro/copy-action@0.0.2
        with:
          # Source file
          source: ./2.txt
          # Target file
          target: /tmp/artifacts
  
       
      

